#!/usr/bin/perl

## Pombert Lab, IIT 2014
## Filters the Contigs.tsv file generated by Ray according to the desired coverage range and minimum length
## Generates a .records file to be used with the faSomeRecords from UCSC (http://hgdownload.cse.ucsc.edu/admin/exe/linux.x86_64/faSomeRecords)

use strict;
use warnings;

my $usage = 'sort_by_coverage.pl min_coverage max_coverage min_size Contigs.tsv';
die $usage unless (scalar@ARGV == 4);

my $min = $ARGV[0];
my $max = $ARGV[1];
my $size = $ARGV[2];
open IN, "<$ARGV[3]";
open LOW, ">Contigs.toolow";
open LOWREC, ">Contigs.toolow.records";
open MID, ">Contigs.good";
open MIDREC, ">Contigs.good.records";
open HIG, ">Contigs.toohigh";
open HIGREC, ">Contigs.toohigh.records";

while (my $line = <IN>){
	chomp $line;
	if ($line =~ /^(contig-\d+)\s+(\d+)\s+(\d+)\s+\d+\s+\d+\s+(\d+)/){
			my $contig = $1;
			my $kmer =$2;
			my $len = $3;
			my $cov = $4;
			my $adj_len = ($len + $kmer - 1);
			if ($adj_len < $size){next;}
			elsif (($cov >= $min)&&($cov <= $max)){
				print MID "$line\n";
				print MIDREC "$contig\n";
			}
			elsif ($cov < $min){
				print LOW "$line\n";
				print LOWREC "$contig\n";
			}
			elsif ($cov > $min){
				print HIG "$line\n";
				print HIGREC "$contig\n";
			}
	}
}